// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	apisresolver "github.com/upbound/provider-aws/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *DataSource) ResolveReferences( // ResolveReferences of this DataSource.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	if mg.Spec.ForProvider.Parameters != nil {
		if mg.Spec.ForProvider.Parameters.S3 != nil {
			if mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.upbound.io", "v1beta2", "Bucket", "BucketList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Bucket),
						Extract:      reference.ExternalName(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.BucketRef,
						Selector:     mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.BucketSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Bucket")
				}
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Bucket = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.BucketRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.ForProvider.Parameters != nil {
		if mg.Spec.ForProvider.Parameters.S3 != nil {
			if mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.upbound.io", "v1beta2", "Object", "ObjectList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Key),
						Extract:      resource.ExtractParamPath("key", false),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.KeyRef,
						Selector:     mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.KeySelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Key")
				}
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Key = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.KeyRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.ForProvider.Parameters != nil {
		if mg.Spec.ForProvider.Parameters.S3 != nil {
			{
				m, l, err = apisresolver.GetManagedResource("iam.aws.upbound.io", "v1beta1", "Role", "RoleList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Parameters.S3.RoleArn),
					Extract:      resource.ExtractParamPath("arn", true),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.Parameters.S3.RoleArnRef,
					Selector:     mg.Spec.ForProvider.Parameters.S3.RoleArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Parameters.S3.RoleArn")
			}
			mg.Spec.ForProvider.Parameters.S3.RoleArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Parameters.S3.RoleArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.Parameters != nil {
		if mg.Spec.InitProvider.Parameters.S3 != nil {
			if mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.upbound.io", "v1beta2", "Bucket", "BucketList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Bucket),
						Extract:      reference.ExternalName(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.BucketRef,
						Selector:     mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.BucketSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Bucket")
				}
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Bucket = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.BucketRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.InitProvider.Parameters != nil {
		if mg.Spec.InitProvider.Parameters.S3 != nil {
			if mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.upbound.io", "v1beta2", "Object", "ObjectList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Key),
						Extract:      resource.ExtractParamPath("key", false),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.KeyRef,
						Selector:     mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.KeySelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Key")
				}
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Key = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.KeyRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.InitProvider.Parameters != nil {
		if mg.Spec.InitProvider.Parameters.S3 != nil {
			{
				m, l, err = apisresolver.GetManagedResource("iam.aws.upbound.io", "v1beta1", "Role", "RoleList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Parameters.S3.RoleArn),
					Extract:      resource.ExtractParamPath("arn", true),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.Parameters.S3.RoleArnRef,
					Selector:     mg.Spec.InitProvider.Parameters.S3.RoleArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Parameters.S3.RoleArn")
			}
			mg.Spec.InitProvider.Parameters.S3.RoleArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Parameters.S3.RoleArnRef = rsp.ResolvedReference

		}
	}

	return nil
}
